apiVersion: v1
kind: Service

metadata:
  name: python-demo-api-svc
  namespace: nodeapi
spec:
  selector:
    app: python-demo-api
  
  ports:
  - protocol: TCP
    name: http
    port: 8000
    targetPort: http