apiVersion: v1
kind: Service

metadata:
  name: node-demo-api-svc
  namespace: nodeapi
spec:
  selector:
    app: node-demo-api
  
  ports:
  - protocol: TCP
    name: http
    port: 3000
    targetPort: http