apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-demo-api
  namespace: nodeapi    
  
  labels:
    app: node-demo-api
    
   
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-demo-api
  template:
    metadata:
      
      labels:
        app: node-demo-api     
      

    spec:
      containers:
        - name: node-demo-api
          image: oscka/node-demo-api
          ports:
          - name: http
            containerPort: 3000