apiVersion: v1
kind: Service

metadata:
  name: java-demo-api-svc
  namespace: api
spec:
  selector:
    app: java-demo-api
  
  ports:
  - protocol: TCP
    name: http
    port: 8080
    targetPort: http