apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-demo-api
  namespace: api    
  
  labels:
    app: java-demo-api
    
   
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-demo-api
  template:
    metadata:
      
      labels:
        app: java-demo-api     
      

    spec:
      containers:
        - name: java-demo-api
          image: oscka/java-demo-api
          ports:
          - name: http
            containerPort: 8080
