apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-demo-api
  namespace: gateway    
  
  labels:
    app: gateway-demo-api
    
   
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-demo-api
  template:
    metadata:
      
      labels:
        app: gateway-demo-api     
      

    spec:
      containers:
        - name: gateway-demo-api
          image: oscka/gateway-demo-api
          ports:
          - name: http
            containerPort: 8080
