apiVersion: v1
kind: Service

metadata:
  name: gateway-demo-api-svc
  namespace: gateway
spec:
  selector:
    app: gateway-demo-api
  
  ports:
  - protocol: TCP
    name: http
    port: 8080
    targetPort: http