apiVersion: v1
kind: Service

metadata:
  name: java-node-api-svc
  namespace: api
spec:
  selector:
    app: java-node-api
  
  ports:
  - protocol: TCP
    name: http
    port: 3000
    targetPort: http